oat-sa/extension-tao-itemqti-pci

views/js/pciCreator/dev/likertScaleInteraction/runtime/css/likertScaleInteraction.css

The style of likert scale interaction was overwritten by TAO's style : padding, margin, etc.
Now it looks a little better.

improved the style of likert scale interaction

---

views/js/pciManager/pciManager.js

improved zip check

---

views/js/pciCreator/dev/likertScaleInteraction/test/commonRenderer.html

related to https://github.com/oat-sa/extension-tao-itemqti/pull/481

Removed qti.css refs

---

manifest.php
scripts/update/Updater.php

Release 4.1.0

---

manifest.php
scripts/update/Updater.php
views/js/pciCreator/dev/audioRecordingInteraction/creator/tpl/propertiesForm.tpl
views/js/pciCreator/dev/audioRecordingInteraction/pciCreator.json

Release 4.5.1

---

composer.json
manifest.php
scripts/update/Updater.php

Release 4.6.2

---

manifest.php
scripts/update/Updater.php
views/js/test/audioRecordingInteraction/test.js

Please verify the following points :

Release 6.1.2

---

manifest.php
scripts/update/Updater.php
test/integration/ImportExportTest.php
test/integration/PciDirectoryParserTest.php
test/integration/PciItemParserTest.php
test/integration/PciManagerTest.php
test/integration/PciPackageParserTest.php
test/integration/PciRegistryTest.php

related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8

Feature/tdr 1/phpunit8 upgrade

---

composer.json
manifest.php

Release 7.0.0

---

.github/workflows/conventional_commits_check.yml
.github/workflows/release_tao_extension.yml

Release 7.2.1

---

model/portableElement/export/ImsPciExporter.php

##Description:
Fixed the relative path exporter
##Ticket: https://oat-sa.atlassian.net/browse/AUT-450
Env:   http://authoring-ionut.playground.kitchen.it.taocloud.org:45841/

fix: fixed the relative path exporter

---

model/portableElement/export/ImsPciExporter.php

Release 7.2.3

---

composer.json
manifest.php
migrations/Version202107271111381465_qtiItemPci.php

Relates to https://oat-sa.atlassian.net/browse/ADF-208

feat: add permission for Item content creator role

---

composer.json
manifest.php
migrations/Version202107271111381465_qtiItemPci.php

Release 7.4.0

---

views/cypress/tests/pci-item-authoring.spec.js

Release 7.6.0

---

views/cypress/tests/pci-item-authoring.spec.js

**Related to:** https://oat-sa.atlassian.net/browse/AUT-965
**How to test:**
Run `views/cypress/tests/pci-item-authoring.spec.js` test

feat: remove interactions test

---

views/cypress/tests/pci-item-authoring.spec.js

Release 7.7.0

---

views/cypress/tests/pci-item-authoring.spec.js

Release 7.11.1

---

controller/PciManager.php
views/js/pciManager/pciManager.js
views/js/pciManager/tpl/listing.tpl

Release 7.13.1

---

controller/PciManager.php

Release 8.0.3

---

controller/PciManager.php
test/integration/PciRegistryTest.php
views/js/pciManager/pciManager.js

Related ticket: https://oat-sa.atlassian.net/browse/ADF-1040
- fixed missing error messages to be shown in some cases
- simplified response json structure
- light refactoring
main issue was exporting a zip package missing required pci assets:
the fix here: https://github.com/oat-sa/extension-tao-itemqti/pull/2181

fix: pci upload

---

.github/workflows/continuous-integration.yaml
composer.json

https://oat-sa.atlassian.net/browse/ADF-1097
https://oat-sa.atlassian.net/browse/ADF-1087
https://oat-sa.atlassian.net/browse/ADF-1105
PHP 8 Migration

chore: update tao-core generis + ci pipeline

---

.github/workflows/continuous-integration.yaml
composer.json

Release 8.5.1

---

model/portableElement/export/ImsPciExporter.php

Release 8.6.4

---

model/portableElement/export/ImsPciExporter.php

Additional fix for https://github.com/oat-sa/extension-tao-itemqti-pci/pull/342

fix: missing modules element

---

model/portableElement/export/ImsPciExporter.php

Release 8.6.5
